name: 'Github Release'
author: 'Lars Gohr'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
description: 'Publish Github releases from an action'
env:
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
inputs:
  name:
    description: 'The name of the release to publish'
    required: true
  file:
    description: 'The file to attach to the release'
args: ['${{ inputs.name }}','{{ inputs.file }}']
runs:
  using: 'docker'
  image: 'Dockerfile'
